<a href="https://colab.research.google.com/github/codevansh/Python-Project/blob/main/learning-data-science--7/jupyter-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.read_csv("housing.csv")

In [10]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41,880,129.0,322,126,8.3252,452600,NEAR BAY
1,-122.22,37.86,21,7099,1106.0,2401,1138,8.3014,358500,NEAR BAY
2,-122.24,37.85,52,1467,190.0,496,177,7.2574,352100,NEAR BAY
3,-122.25,37.85,52,1274,235.0,558,219,5.6431,341300,NEAR BAY
4,-122.25,37.85,52,1627,280.0,565,259,3.8462,342200,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25,1665,374.0,845,330,1.5603,78100,INLAND
20636,-121.21,39.49,18,697,150.0,356,114,2.5568,77100,INLAND
20637,-121.22,39.43,17,2254,485.0,1007,433,1.7000,92300,INLAND
20638,-121.32,39.43,18,1860,409.0,741,349,1.8672,84700,INLAND
20639,-121.24,39.37,16,2785,616.0,1387,530,2.3886,89400,INLAND

In [11]:
df["income_cat"] = pd.cut(df['median_income'], bins =[0,1.5,3.0,4.5,6.0, np.inf], labels=[1,2,3,4,5])

In [12]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(df,df['income_cat']):
  strata_train_set = df.loc[train_index]
  strata_test_set = df.loc[test_index]

In [14]:
df = strata_train_set.copy()

In [15]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,income_cat
12655,-121.46,38.52,29,3873,797.0,2237,706,2.1736,72100,INLAND,2
15502,-117.23,33.09,7,5320,855.0,2015,768,6.3373,279600,NEAR OCEAN,5
2908,-119.04,35.37,44,1618,310.0,667,300,2.8750,82700,INLAND,2
14053,-117.13,32.75,24,1877,519.0,898,483,2.2264,112500,NEAR OCEAN,2
20496,-118.70,34.28,27,3536,646.0,1837,580,4.4964,238300,<1H OCEAN,3
...,...,...,...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14,6665,1231.0,2026,1001,5.0900,268500,<1H OCEAN,4
12661,-121.42,38.51,15,7901,1422.0,4769,1418,2.8139,90400,INLAND,2
19263,-122.72,38.44,48,707,166.0,458,172,3.1797,140400,<1H OCEAN,3
19140,-122.70,38.31,14,3155,580.0,1208,501,4.1964,258100,<1H OCEAN,3
19773,-122.14,39.97,27,1079,222.0,625,197,3.1319,62700,INLAND,3

In [16]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

In [20]:
my_Pipeline = Pipeline([
  ("impute", SimpleImputer(strategy="median")),
   ('standardize',StandardScaler())
])

# pipelines are used to implement too many updations on the data at once in a single cell.

In [19]:
housing = df.drop('ocean_proximity',axis=1)

In [21]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,income_cat
12655,-121.46,38.52,29,3873,797.0,2237,706,2.1736,72100,2
15502,-117.23,33.09,7,5320,855.0,2015,768,6.3373,279600,5
2908,-119.04,35.37,44,1618,310.0,667,300,2.8750,82700,2
14053,-117.13,32.75,24,1877,519.0,898,483,2.2264,112500,2
20496,-118.70,34.28,27,3536,646.0,1837,580,4.4964,238300,3
...,...,...,...,...,...,...,...,...,...,...
15174,-117.07,33.03,14,6665,1231.0,2026,1001,5.0900,268500,4
12661,-121.42,38.51,15,7901,1422.0,4769,1418,2.8139,90400,2
19263,-122.72,38.44,48,707,166.0,458,172,3.1797,140400,3
19140,-122.70,38.31,14,3155,580.0,1208,501,4.1964,258100,3
19773,-122.14,39.97,27,1079,222.0,625,197,3.1319,62700,3

In [22]:
my_Pipeline.fit_transform(housing)

array([[-0.94135046,  1.34743822,  0.02756357, ..., -0.8936472 ,
        -1.16601465, -0.95468705],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  1.292168  ,
         0.62745084,  1.89007821],
       [ 0.26758118, -0.1259716 ,  1.22045984, ..., -0.52543365,
        -1.07439665, -0.95468705],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ..., -0.36547546,
        -0.5756836 , -0.00643196],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.16826095,
         0.44162188, -0.00643196],
       [-1.28105026,  2.02567448, -0.13148926, ..., -0.390569  ,
        -1.2472608 , -0.00643196]])