<a href="https://colab.research.google.com/github/codevansh/Python-Project/blob/main/learning-data-science--4/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# learning machine learning

In [55]:
import pandas as pd
import numpy as np

np.random.seed(42)

num_rows = 1000
data = {
    "camera": np.random.randint(8, 201, size=num_rows),
    "age": np.random.randint(0, 4, size=num_rows),
    "ram": np.random.choice([4, 6, 8, 12, 16], size=num_rows),
    "cpu_score": np.random.randint(40, 101, size=num_rows),
    "slot_sd": np.random.randint(0, 2, size=num_rows),
    "sims": np.random.choice([1, 2], size=num_rows),
    "price": np.random.randint(8000, 70001, size=num_rows),
}


df = pd.DataFrame(data)

df.to_csv("mobile_data.csv", index=False)

print(df.head())

   camera  age  ram  cpu_score  slot_sd  sims  price
0     110    2    4         89        1     2  31596
1     187    0    4         42        0     1  33530
2     100    2    4         52        0     2   9262
3      22    2    6         82        0     2  62199
4     114    2   12         88        1     1  66287

you can use kaggle and OpenML for datasets

In [56]:
import pandas as pd
from sklearn.naive_bayes import GaussianNB

In [57]:
data = pd.read_excel('iris-train.xlsx')

In [58]:
data.head()

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm,class
0,7.9,3.8,6.4,2.0,Iris-virginica
1,7.7,3.8,6.7,2.2,Iris-virginica
2,7.7,2.6,6.9,2.3,Iris-virginica
3,7.7,2.8,6.7,2.0,Iris-virginica
4,7.7,3.0,6.1,2.3,Iris-virginica

In [59]:
x = data.iloc[:,:-1]

In [60]:
y = data.iloc[:,-1]

In [61]:
model = GaussianNB()

In [62]:
x

,sepal length in cm,sepal width in cm,petal length in cm,petal width in cm
0,7.9,3.8,6.4,2.0
1,7.7,3.8,6.7,2.2
2,7.7,2.6,6.9,2.3
3,7.7,2.8,6.7,2.0
4,7.7,3.0,6.1,2.3
...,...,...,...,...
111,4.5,2.3,1.3,0.3
112,4.4,2.9,1.4,0.2
113,4.4,3.0,1.3,0.2
114,4.4,3.2,1.3,0.2
115,4.3,3.0,1.1,0.1

In [63]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: class, Length: 116, dtype: object

In [64]:
model = model.fit(x,y)

In [65]:
predictions = model.predict([[5.2,	3.5,	1.5,	0.2]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [66]:
predictions

array(['Iris-setosa'], dtype='<U15')

In [67]:
datatest = pd.read_excel('iris-test.xlsx')

In [68]:
xtest = datatest.iloc[:,:-1]

In [69]:
predictions = model.predict(xtest.values)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(

In [70]:
predictions

array(['Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype='<U15')

In [71]:
ytest = datatest.iloc[:,-1]

In [72]:
actual = ytest.values

In [73]:
count = 0
for i in range(0, len(actual)):
  if actual[i] == predictions[i]:
    count = count + 1
print((count*100)/len(actual))

97.05882352941177